package com.sparta.fintech.ledger.domain;

public enum ReconciliationTargetType {

    ACCOUNT_BALANCE_VS_ACCOUNT_TRANSACTION,

    TRANSACTION_VS_ACCOUNT_TRANSACTION,

    ACCOUNT_TRANSACTION_VS_ACCOUNTING_LEDGER,

    ACCOUNTING_LEDGER_DEBIT_VS_CREDIT,

    SUCCESS_TRANSACTION_MISSING_LEDGER_OR_JOURNAL,

    INCOMPLETE_TRANSACTION_HAS_POSTINGS,

    COMPLETED_TRANSACTION_MISSING_COMPLETION_TIME,

    API_TRANSFER_ORDER
}
