package com.sparta.fintech.ledger.domain;

public enum ReconciliationTargetType {

    ACCOUNT_BALANCE_VS_ACCOUNT_TRANSACTION,

    TRANSACTION_VS_ACCOUNT_TRANSACTION,

    ACCOUNT_TRANSACTION_VS_ACCOUNTING_LEDGER,

    ACCOUNTING_LEDGER_DEBIT_VS_CREDIT,


    INCOMPLETE_TRANSACTION_HAS_POSTINGS,


    API_TRANSFER_ORDER
}
